samples:
    OG0005921: Single_Copy_Orthologue_Sequences/OG0005921.fa
    OG0005923: Single_Copy_Orthologue_Sequences/OG0005923.fa
    OG0005924: Single_Copy_Orthologue_Sequences/OG0005924.fa
    OG0005929: Single_Copy_Orthologue_Sequences/OG0005929.fa
    OG0005931: Single_Copy_Orthologue_Sequences/OG0005931.fa
    OG0005935: Single_Copy_Orthologue_Sequences/OG0005935.fa
    OG0005942: Single_Copy_Orthologue_Sequences/OG0005942.fa
    OG0005948: Single_Copy_Orthologue_Sequences/OG0005948.fa
    OG0005949: Single_Copy_Orthologue_Sequences/OG0005949.fa
    OG0005950: Single_Copy_Orthologue_Sequences/OG0005950.fa
    OG0005953: Single_Copy_Orthologue_Sequences/OG0005953.fa
    OG0005956: Single_Copy_Orthologue_Sequences/OG0005956.fa
    OG0005957: Single_Copy_Orthologue_Sequences/OG0005957.fa
    OG0005958: Single_Copy_Orthologue_Sequences/OG0005958.fa
    OG0005960: Single_Copy_Orthologue_Sequences/OG0005960.fa
    OG0005962: Single_Copy_Orthologue_Sequences/OG0005962.fa
    OG0005965: Single_Copy_Orthologue_Sequences/OG0005965.fa
    OG0005966: Single_Copy_Orthologue_Sequences/OG0005966.fa
    OG0005967: Single_Copy_Orthologue_Sequences/OG0005967.fa
    OG0005969: Single_Copy_Orthologue_Sequences/OG0005969.fa
    OG0005972: Single_Copy_Orthologue_Sequences/OG0005972.fa
    OG0005974: Single_Copy_Orthologue_Sequences/OG0005974.fa
    OG0005976: Single_Copy_Orthologue_Sequences/OG0005976.fa
    OG0005977: Single_Copy_Orthologue_Sequences/OG0005977.fa
    OG0005987: Single_Copy_Orthologue_Sequences/OG0005987.fa
    OG0005988: Single_Copy_Orthologue_Sequences/OG0005988.fa
    OG0005990: Single_Copy_Orthologue_Sequences/OG0005990.fa
    OG0005992: Single_Copy_Orthologue_Sequences/OG0005992.fa
    OG0006001: Single_Copy_Orthologue_Sequences/OG0006001.fa
    OG0006002: Single_Copy_Orthologue_Sequences/OG0006002.fa
    OG0006009: Single_Copy_Orthologue_Sequences/OG0006009.fa
    OG0006010: Single_Copy_Orthologue_Sequences/OG0006010.fa
    OG0006011: Single_Copy_Orthologue_Sequences/OG0006011.fa
    OG0006016: Single_Copy_Orthologue_Sequences/OG0006016.fa
    OG0006021: Single_Copy_Orthologue_Sequences/OG0006021.fa
    OG0006023: Single_Copy_Orthologue_Sequences/OG0006023.fa
    OG0006024: Single_Copy_Orthologue_Sequences/OG0006024.fa
    OG0006026: Single_Copy_Orthologue_Sequences/OG0006026.fa
    OG0006030: Single_Copy_Orthologue_Sequences/OG0006030.fa
    OG0006031: Single_Copy_Orthologue_Sequences/OG0006031.fa
    OG0006032: Single_Copy_Orthologue_Sequences/OG0006032.fa
    OG0006033: Single_Copy_Orthologue_Sequences/OG0006033.fa
    OG0006037: Single_Copy_Orthologue_Sequences/OG0006037.fa
    OG0006039: Single_Copy_Orthologue_Sequences/OG0006039.fa
    OG0006041: Single_Copy_Orthologue_Sequences/OG0006041.fa
    OG0006043: Single_Copy_Orthologue_Sequences/OG0006043.fa
    OG0006044: Single_Copy_Orthologue_Sequences/OG0006044.fa
    OG0006048: Single_Copy_Orthologue_Sequences/OG0006048.fa
    OG0006050: Single_Copy_Orthologue_Sequences/OG0006050.fa
    OG0006053: Single_Copy_Orthologue_Sequences/OG0006053.fa
    OG0006054: Single_Copy_Orthologue_Sequences/OG0006054.fa
    OG0006056: Single_Copy_Orthologue_Sequences/OG0006056.fa
    OG0006057: Single_Copy_Orthologue_Sequences/OG0006057.fa
    OG0006062: Single_Copy_Orthologue_Sequences/OG0006062.fa
    OG0006063: Single_Copy_Orthologue_Sequences/OG0006063.fa
    OG0006064: Single_Copy_Orthologue_Sequences/OG0006064.fa
    OG0006067: Single_Copy_Orthologue_Sequences/OG0006067.fa
    OG0006068: Single_Copy_Orthologue_Sequences/OG0006068.fa
    OG0006069: Single_Copy_Orthologue_Sequences/OG0006069.fa
    OG0006074: Single_Copy_Orthologue_Sequences/OG0006074.fa
    OG0006075: Single_Copy_Orthologue_Sequences/OG0006075.fa
    OG0006076: Single_Copy_Orthologue_Sequences/OG0006076.fa
    OG0006077: Single_Copy_Orthologue_Sequences/OG0006077.fa
    OG0006078: Single_Copy_Orthologue_Sequences/OG0006078.fa
    OG0006079: Single_Copy_Orthologue_Sequences/OG0006079.fa
    OG0006084: Single_Copy_Orthologue_Sequences/OG0006084.fa
    OG0006086: Single_Copy_Orthologue_Sequences/OG0006086.fa
    OG0006090: Single_Copy_Orthologue_Sequences/OG0006090.fa
    OG0006094: Single_Copy_Orthologue_Sequences/OG0006094.fa
    OG0006097: Single_Copy_Orthologue_Sequences/OG0006097.fa
    OG0006102: Single_Copy_Orthologue_Sequences/OG0006102.fa
    OG0006109: Single_Copy_Orthologue_Sequences/OG0006109.fa
    OG0006111: Single_Copy_Orthologue_Sequences/OG0006111.fa
    OG0006112: Single_Copy_Orthologue_Sequences/OG0006112.fa
    OG0006114: Single_Copy_Orthologue_Sequences/OG0006114.fa
    OG0006115: Single_Copy_Orthologue_Sequences/OG0006115.fa
    OG0006118: Single_Copy_Orthologue_Sequences/OG0006118.fa
    OG0006119: Single_Copy_Orthologue_Sequences/OG0006119.fa
    OG0006122: Single_Copy_Orthologue_Sequences/OG0006122.fa
    OG0006123: Single_Copy_Orthologue_Sequences/OG0006123.fa
    OG0006126: Single_Copy_Orthologue_Sequences/OG0006126.fa
    OG0006128: Single_Copy_Orthologue_Sequences/OG0006128.fa
    OG0006129: Single_Copy_Orthologue_Sequences/OG0006129.fa
    OG0006130: Single_Copy_Orthologue_Sequences/OG0006130.fa
    OG0006134: Single_Copy_Orthologue_Sequences/OG0006134.fa
    OG0006135: Single_Copy_Orthologue_Sequences/OG0006135.fa
    OG0006136: Single_Copy_Orthologue_Sequences/OG0006136.fa
    OG0006140: Single_Copy_Orthologue_Sequences/OG0006140.fa
    OG0006141: Single_Copy_Orthologue_Sequences/OG0006141.fa
    OG0006146: Single_Copy_Orthologue_Sequences/OG0006146.fa
    OG0006147: Single_Copy_Orthologue_Sequences/OG0006147.fa
    OG0006148: Single_Copy_Orthologue_Sequences/OG0006148.fa
    OG0006150: Single_Copy_Orthologue_Sequences/OG0006150.fa
    OG0006154: Single_Copy_Orthologue_Sequences/OG0006154.fa
    OG0006157: Single_Copy_Orthologue_Sequences/OG0006157.fa
    OG0006159: Single_Copy_Orthologue_Sequences/OG0006159.fa
    OG0006166: Single_Copy_Orthologue_Sequences/OG0006166.fa
    OG0006171: Single_Copy_Orthologue_Sequences/OG0006171.fa
    OG0006179: Single_Copy_Orthologue_Sequences/OG0006179.fa
    OG0006181: Single_Copy_Orthologue_Sequences/OG0006181.fa
    OG0006185: Single_Copy_Orthologue_Sequences/OG0006185.fa
    OG0006186: Single_Copy_Orthologue_Sequences/OG0006186.fa
    OG0006187: Single_Copy_Orthologue_Sequences/OG0006187.fa
    OG0006189: Single_Copy_Orthologue_Sequences/OG0006189.fa
    OG0006191: Single_Copy_Orthologue_Sequences/OG0006191.fa
    OG0006197: Single_Copy_Orthologue_Sequences/OG0006197.fa
    OG0006202: Single_Copy_Orthologue_Sequences/OG0006202.fa
    OG0006204: Single_Copy_Orthologue_Sequences/OG0006204.fa
    OG0006205: Single_Copy_Orthologue_Sequences/OG0006205.fa
    OG0006206: Single_Copy_Orthologue_Sequences/OG0006206.fa
    OG0006213: Single_Copy_Orthologue_Sequences/OG0006213.fa
    OG0006216: Single_Copy_Orthologue_Sequences/OG0006216.fa
    OG0006221: Single_Copy_Orthologue_Sequences/OG0006221.fa
    OG0006225: Single_Copy_Orthologue_Sequences/OG0006225.fa
    OG0006226: Single_Copy_Orthologue_Sequences/OG0006226.fa
    OG0006228: Single_Copy_Orthologue_Sequences/OG0006228.fa
    OG0006229: Single_Copy_Orthologue_Sequences/OG0006229.fa
    OG0006231: Single_Copy_Orthologue_Sequences/OG0006231.fa
    OG0006232: Single_Copy_Orthologue_Sequences/OG0006232.fa
    OG0006233: Single_Copy_Orthologue_Sequences/OG0006233.fa
    OG0006236: Single_Copy_Orthologue_Sequences/OG0006236.fa
    OG0006238: Single_Copy_Orthologue_Sequences/OG0006238.fa
    OG0006244: Single_Copy_Orthologue_Sequences/OG0006244.fa
    OG0006248: Single_Copy_Orthologue_Sequences/OG0006248.fa
    OG0006249: Single_Copy_Orthologue_Sequences/OG0006249.fa
    OG0006251: Single_Copy_Orthologue_Sequences/OG0006251.fa
    OG0006255: Single_Copy_Orthologue_Sequences/OG0006255.fa
    OG0006258: Single_Copy_Orthologue_Sequences/OG0006258.fa
    OG0006260: Single_Copy_Orthologue_Sequences/OG0006260.fa
    OG0006261: Single_Copy_Orthologue_Sequences/OG0006261.fa
    OG0006269: Single_Copy_Orthologue_Sequences/OG0006269.fa
    OG0006270: Single_Copy_Orthologue_Sequences/OG0006270.fa
    OG0006277: Single_Copy_Orthologue_Sequences/OG0006277.fa
    OG0006278: Single_Copy_Orthologue_Sequences/OG0006278.fa
    OG0006280: Single_Copy_Orthologue_Sequences/OG0006280.fa
    OG0006286: Single_Copy_Orthologue_Sequences/OG0006286.fa
    OG0006288: Single_Copy_Orthologue_Sequences/OG0006288.fa
    OG0006289: Single_Copy_Orthologue_Sequences/OG0006289.fa
    OG0006295: Single_Copy_Orthologue_Sequences/OG0006295.fa
    OG0006299: Single_Copy_Orthologue_Sequences/OG0006299.fa
    OG0006301: Single_Copy_Orthologue_Sequences/OG0006301.fa
    OG0006303: Single_Copy_Orthologue_Sequences/OG0006303.fa
    OG0006304: Single_Copy_Orthologue_Sequences/OG0006304.fa
    OG0006305: Single_Copy_Orthologue_Sequences/OG0006305.fa
    OG0006311: Single_Copy_Orthologue_Sequences/OG0006311.fa
    OG0006313: Single_Copy_Orthologue_Sequences/OG0006313.fa
    OG0006322: Single_Copy_Orthologue_Sequences/OG0006322.fa
    OG0006324: Single_Copy_Orthologue_Sequences/OG0006324.fa
    OG0006326: Single_Copy_Orthologue_Sequences/OG0006326.fa
    OG0006327: Single_Copy_Orthologue_Sequences/OG0006327.fa
    OG0006330: Single_Copy_Orthologue_Sequences/OG0006330.fa